name: node
     
on:
  push:
   branches: [ main ]
jobs:
   build:
      runs-on: python
      steps:
       - uses: actions/checkout@v2
    
       - name: installing dependencies
          run: cd /mern_dairy/client
               npm install
       - name: running a build file
          run: cd /mern_dairy/client
               npm run build
       - name: nginx service
          run: |
                service nginx restart
                service nginx status      
