name: node
     
on:
  push:
   branches: [ main ]
jobs:
   build:
      runs-on: js
      steps: 
       - uses: actions/checkout@v2
       - name: installing dependencies
         run: |
               cd /home/ubuntu/actions-runner/_work/mern/mern/mern_diary/client
               npm install
       - name: running a build file
         run: |
               cd /home/ubuntu/actions-runner/_work/mern/mern/mern_diary/client            
                npm run build
       - name: nginx service
         run: |
                service nginx restart
                service nginx status      
