name: node
     
on:
  push:
   branches: [ main ]
jobs:
   build:
      runs-on: js
      steps:    
       - name: installing dependencies
         run: |
                npm install
       - name: running a build file
         run: |
                npm run build
       - name: nginx service
         run: |
                service nginx restart
                service nginx status      
