name: node
     
on:
  push:
   branches: [ main ]
jobs:
   build:
      runs-on: js
      steps: 
       - uses: actions/checkout@v2
       - name: installing dependencies
         run: |
               cd client
                npm install
       - name: running a build file
         run: |
               cd client             
                npm run build
       - name: nginx service
         run: |
                service nginx restart
                service nginx status      
