name: node
     
on:
  push:
   branches: [ main ]
jobs:
   build:
      runs-on: python
      steps:
       - uses: actions/checkout@v2
    
        - name: installing dependencies
          uses: cd client
                npm install

    -name: running a build file
     uses: cd client
           npm run build
    -name: nginx service
     uses: |
            service nginx restart
            service nginx status      
